### ISSUE TITLE
Overlapping Title

### ISSUE THREAD

**Issue by TrueBankai416** [tedhinklater/finality#1]
Jellyfin Server 10.9.6
Browser Firefox

![image](https://github.com/tedhinklater/finality/assets/97103466/4985eab6-c034-465b-ad24-c6c9b6ff73cc)

**Comment by TrueBankai416** [comment]
Fixed this by adjusting the Top position
```
.layout-desktop .detailPagePrimaryContent {
  position: fixed;
  top: 30.5em;
  left: 7.48em;
  max-width: 50%;
  font-size: 10pt;
}
```
Then on some media the `Watch Now` was almost overlapping
![image](https://github.com/tedhinklater/finality/assets/97103466/8751fb26-eef3-4903-9ad3-f0786299b423)

So i also adjusted that
```
.layout-desktop .mainDetailButtons {
  -webkit-align-items: center;
  align-items: center;
  display: flex;
  position: fixed;
  top: 17.3em;
  left: 2.5em;
  font-size: 200%;
}
```
```
.layout-desktop .detailButton .detailButton-icon.play_arrow::after {
    content: "WATCH NOW";
	font-family: "Kanit", sans-serif;
    font-weight: 400;
    font-style: normal;
    position: fixed;
    top: 36.75em;
	left: 9.5em;
    color: white;
    font-weight: bold;
    font-size: 12pt;
    white-space: nowrap;
	z-index: 2;
}

.layout-desktop .detailButton .detailButton-icon.theaters {
    position: fixed;
    top: 12.0em;
	left: 12.3em;
    font-weight: bold;
    font-size: 12pt;
    white-space: nowrap;
	padding-right: 2.4em;
}

.layout-desktop .detailButton .detailButton-icon.check.playstatebutton-icon-unplayed {
    position: fixed;
    top: 12.0em;
    left: 6.5em;
    font-weight: bold; 
    font-size: 10pt;
    white-space: nowrap;
}

.layout-desktop .detailButton .detailButton-icon.check.playstatebutton-icon-played {
    position: fixed;
    top: 12.0em;
	left: 6.5em;
    font-weight: bold;
    font-size: 10pt;
    white-space: nowrap;
}

.layout-desktop .detailButton .detailButton-icon.favorite {
    position: fixed;
    top: 12.0em;
	left: 8.5em;
    font-weight: bold;
    font-size: 12pt;
    white-space: nowrap;
}

.layout-desktop .detailButton .detailButton-icon.replay {
    display: none;
}

.layout-desktop .detailButton .detailButton-icon.shuffle {
    display: none;
}

.layout-desktop .detailButton .detailButton-icon.more_vert {
    position: fixed;
    top: 12.0em;
	left: 10.5em;
    font-weight: bold;
    font-size: 12pt;
    white-space: nowrap;
}
```
![image](https://github.com/tedhinklater/finality/assets/97103466/ac3af3c0-53bc-445d-8afc-dcfb6da9db4f)

![image](https://github.com/tedhinklater/finality/assets/97103466/97d8db33-7dce-490e-ad18-de605b2966ff)

**Comment by tedhinklater** [comment]
Thank you so much for catching these I'll get the fixes in asap

**Comment by TrueBankai416** [comment]
I mean i doubt that you have a title that long in your library haha

**Comment by tedhinklater** [comment]
I just checked "Borat! Cultural Learnings of America for Make Benefit Glorious Nation of Kazakhstan" and it was 4 lines @.@ and making enough room for that left way too much space between the title and description, so it's now 2 lines and ellipsis for anything longer than that.

**Comment by TrueBankai416** [comment]
May need to adjust it a bit more 
![image](https://github.com/tedhinklater/finality/assets/97103466/c5238cb1-8c55-4c01-98a9-360300567077)

**Comment by tedhinklater** [comment]
could you possibly

**Comment by TrueBankai416** [comment]
yea ill make the changes tomorrow

**Comment by tedhinklater** [comment]
> yea ill make the changes tomorrow

Thank you so much! I think it's "seriesAirTime" not sure, it doesn't show for me

.layout-desktop #itemDetailPage .seriesAirTime {
  display: none;
}

or give it a fixed position if you want to keep it.

Thanks again.

**Comment by TrueBankai416** [comment]
I fixed it previously by moving the buttons down. The air time seems to be just below the details (not sure why the details box is so large)

Sent from Proton Mail Android

-------- Original Message --------

**Comment by TrueBankai416** [comment]
im having trouble modifying it, I think it would look good under the title and over to the right. Im not sure if this screenshot will show you anything
![image](https://github.com/tedhinklater/finality/assets/97103466/50609afb-4f24-4db2-9622-dc4b99917ac7)

**Comment by TrueBankai416** [comment]
I figured it out. its 
```
.layout-desktop #itemDetailPage .detailSectionContent #seriesAirTime
```

**Comment by TrueBankai416** [comment]
```
/* Series Air Time */

.layout-desktop #itemDetailPage .detailSectionContent #seriesAirTime {
	position: fixed;
	top: 7.3em;
    left: 23em;
}
```

**Comment by tedhinklater** [comment]
I can't see it but well done! 🎉 & thanks again

**Comment by TrueBankai416** [comment]
> I just checked "Borat! Cultural Learnings of America for Make Benefit Glorious Nation of Kazakhstan" and it was 4 lines @.@ and making enough room for that left way too much space between the title and description, so it's now 2 lines and ellipsis for anything longer than that.

How did you do this?

**Comment by TrueBankai416** [comment]
> I can't see it but well done! 🎉 & thanks again

I ended up putting it up top next to the ratings

**Comment by tedhinklater** [comment]
Ahh good idea
