### ISSUE TITLE
No Scrolling Down

### ISSUE THREAD

**Issue by DevilsDesigns** [tedhinklater/finality#10]
is this intentional where i cannot scroll down to view cast
![image](https://github.com/tedhinklater/finality/assets/35183970/52969430-3b1e-40d9-807e-15cc4587a234)

**Comment by DevilsDesigns** [comment]
btw thats the full browser window. it cuts off the cast on the bottom
![image](https://github.com/tedhinklater/finality/assets/35183970/5ad07fe6-89dc-453e-bfb8-e649dd8a6253)

**Comment by TrueBankai416** [comment]
no issue on my end

![image](https://github.com/tedhinklater/finality/assets/97103466/467cb461-4e4e-4128-acf1-61efab3b9539)

**Comment by TrueBankai416** [comment]
wait actually let me paste the new code directly and try again. I saw that the spacing got changed again in the last pull

**Comment by DevilsDesigns** [comment]
if i bring it down to 90% it shows 
![image](https://github.com/tedhinklater/finality/assets/35183970/6523813c-4151-47b2-8e8d-f8cdcfe20c7f)

**Comment by TrueBankai416** [comment]
just pasted the updated css directly and no change. Mine is showing as expected at 100%. Only on fullscreen mode though

**Comment by DevilsDesigns** [comment]
> just pasted the updated css directly and no change. Mine is showing as expected at 100%. Only on fullscreen mode though

are you on an ultradwide. Could that be an issue

**Comment by TrueBankai416** [comment]
> > just pasted the updated css directly and no change. Mine is showing as expected at 100%. Only on fullscreen mode though
> 
> are you on an ultradwide. Could that be an issue

Im on a 17in Laptop

**Comment by DevilsDesigns** [comment]
when i go to f11 in firefox for fullscreen it automatically fixes it but in browser without f11 it doesnt at 100%
![image](https://github.com/tedhinklater/finality/assets/35183970/c28a818d-c044-4cb8-835a-9ed45cc88116)
