### ISSUE TITLE
Gradient Playback bar

### ISSUE THREAD

**Issue by TrueBankai416** [tedhinklater/finality#11]
This bar is red all the way across. I would expect it to be maybe gray to the right of the `watched` portion

![image](https://github.com/tedhinklater/finality/assets/97103466/a9592e56-f513-4bbd-bd81-c00fdebd7d18)

**Comment by DevilsDesigns** [comment]
i thinks it because of the important pull i made

**Comment by TrueBankai416** [comment]
> i thinks it because of the important pull i made

im looking into it rn

**Comment by tedhinklater** [comment]
.playbackProgress background-color: #000!important fixed it
