### ISSUE TITLE
Scrolling Actors

### ISSUE THREAD

**Issue by DevilsDesigns** [tedhinklater/finality#12]
![image](https://github.com/tedhinklater/finality/assets/35183970/5c3dde93-9e19-4742-805f-663aca734276)
You Should make a scrolling like for the season or episodes for the actors. im not sure if this is possible but would be great to implement

**Comment by tedhinklater** [comment]
This is the next thing really, it's just setting the position to Relative to allow scrolling is tricky but doable

**Comment by tedhinklater** [comment]
I did think that was too easy
