### ISSUE TITLE
Large Collections

### ISSUE THREAD

**Issue by Giggles22031** [tedhinklater/finality#17]
Having large collections causes the movies to take up multiple lines, making them overlap with the collection cover and text throughout the page.

![image](https://github.com/tedhinklater/finality/assets/55936164/7b4bc3b0-3997-4af9-9ad2-ca5b473950d1)

**Comment by tedhinklater** [comment]
Thanks for letting me know, I'll fix it today!

**Comment by tedhinklater** [comment]
![collections](https://github.com/tedhinklater/finality/assets/66086488/387fb69f-80f9-473b-b419-8e74a5e0a451)
