### ISSUE TITLE
Smart TV?

### ISSUE THREAD

**Issue by DumberSoft** [tedhinklater/finality#18]
Consult, there will be in the future so that it is visible for Smart TV since when I put it in TV mode the modifications do not appear.

**Comment by tedhinklater** [comment]
Hi I'll get to work on it right now

**Comment by tedhinklater** [comment]
TV mode is... well it works! I'll make it more accurate to desktop mode. The main thing is Jellyfin's TV Mode doesn't support logos yet :/ 

but according to this it's being added soon (hopefully)
https://github.com/jellyfin/jellyfin-web/pull/5620

I'll keep updating

**Comment by DumberSoft** [comment]
I recommend you in show when you select it is marking in red, since it only comes out as a zoom, in TV mode

**Comment by DumberSoft** [comment]
https://i.imgur.com/hlbj1B3.jpeg

**Comment by tedhinklater** [comment]
> https://i.imgur.com/hlbj1B3.jpeg

It should look like this now ![tv](https://github.com/tedhinklater/finality/assets/66086488/21d13106-530c-4ffa-a221-bd9c89af16c1)

Can I ask, is that the "More Like This" section along the top in your picture? It should be at the side...
