### ISSUE TITLE
Cast is cutoff and unable to scroll

### ISSUE THREAD

**Issue by TrueBankai416** [tedhinklater/finality#2]
Server 10.9.6
Browser Firefox

![image](https://github.com/tedhinklater/finality/assets/97103466/108e22f7-461f-43b0-92c3-eaa058c81a19)

**Comment by tedhinklater** [comment]
have you used Ctrl+Shift+B to hide your bookmarks bar or F11 to fullscreen?

**Comment by TrueBankai416** [comment]
Full screen does work as intended

Sent from Proton Mail Android

-------- Original Message --------

**Comment by tedhinklater** [comment]
Thank you very much :D
