### ISSUE TITLE
Ability to remove or set the jellyfin logo to something different

### ISSUE THREAD

**Issue by nxllxvxid** [tedhinklater/finality#20]
I have most of my server themed around my sort of branding except for that I was wondering if maybe you could help me figure out how to overwrite that with my own?

![image](https://github.com/tedhinklater/finality/assets/19805594/29296e65-0d80-481b-a8b6-fa113f8ed3d2)

**Comment by tedhinklater** [comment]
```
.pageTitleWithDefaultLogo {
  background-image: url(https://i.imgur.com/5d4W3M2.png);
}
```

You can either change the URL to your own pic or change it to 

display: none; 

to remove it

**Comment by nxllxvxid** [comment]
Thank you so much that worked perfectly I would suggest maybe adding it to the readme for people who like to brand their server possibly
