### ISSUE TITLE
Home Screen Appearance for 1440

### ISSUE THREAD

**Issue by nxllxvxid** [tedhinklater/finality#22]
![image](https://github.com/tedhinklater/finality/assets/19805594/0d7c8902-2b40-4e24-a142-2e862e7b1396)
Everything seems to be a bit skewed towards the left as apposed to filling up the screen I also believe that for some reason it isn't picking up the css edits for this like the movies, live tv, etc as mine appear the same as in stock JF

**Comment by tedhinklater** [comment]
Ahaaaa I turned on Virtual Super Resolution, set it to 1440p and it looks like yours does. I'll be able to work on the 1440p+ layouts with this

**Comment by tedhinklater** [comment]
> for some reason it isn't picking up the css edits for this like the movies, live tv, etc

I just made some cards in photoshop

https://imgur.com/a/BlqMCwV

**Comment by tedhinklater** [comment]
1440p support added!

**Comment by nxllxvxid** [comment]
> 1440p support added! I've purged the jsdelivr cache but it might take a while to show the changes



> 1440p support added! I've purged the jsdelivr cache but it might take a while to show the changes

Fuck yeah you are amazing thank you so much, like I said I love the theme it's beautiful I can't wait to see it working perfectly for 1440 :))))))

**Comment by tedhinklater** [comment]
It's up, might have to clear your cache
