### ISSUE TITLE
Album Appearance 1440

### ISSUE THREAD

**Issue by nxllxvxid** [tedhinklater/finality#23]
![image](https://github.com/tedhinklater/finality/assets/19805594/57bcb318-4862-421a-a441-9776560d8a46)
I am not sure if the logo clipping with the tracklist is intentional

**Comment by tedhinklater** [comment]
![tracklist](https://github.com/tedhinklater/finality/assets/66086488/f1edcc60-2468-41e4-8d5e-03afb564ca7a)

Extended the tracklist to cover the logo

**Comment by nxllxvxid** [comment]
> ![tracklist](https://private-user-images.githubusercontent.com/66086488/344313448-f1edcc60-2468-41e4-8d5e-03afb564ca7a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjAzMTUwMjcsIm5iZiI6MTcyMDMxNDcyNywicGF0aCI6Ii82NjA4NjQ4OC8zNDQzMTM0NDgtZjFlZGNjNjAtMjQ2OC00MWU0LThkNWUtMDNhZmI1NjRjYTdhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzA3VDAxMTIwN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQxYWIwYjM0YThjNDMxMGUxYjNhNDU1NDQ3ZmU1M2IxNTQ2YTdiN2ZiNDI4MzA3MGJmMjc5OTFiODAzZDFjNTcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.zkqZWc68KAMBfZdfJ5MzVHUu4xwv9I9h9UQK0D5-FiI)
> 
> Extended the tracklist to cover the logo

idk if you want to or if you think it would be a good idea but I think that if you are able to moving the logo underneath the album would be a nice place cause then it can be seen

**Comment by tedhinklater** [comment]
I've moved the tracks down to show the logo
![Screenshot from 2024-07-07 04-39-56](https://github.com/tedhinklater/finality/assets/66086488/5e3d521b-0308-44c9-8a38-df7779f1210e)

it does mean the Episodes list moves down too (they're one & the same) but not the end of the world
![Screenshot from 2024-07-07 04-41-44](https://github.com/tedhinklater/finality/assets/66086488/c80fec31-7b3f-4dc4-9521-42dde004a972)

**Comment by nxllxvxid** [comment]
that actually looks really nice sorry I keep coming in with shit lmao

**Comment by tedhinklater** [comment]
Nah seriously thanks for letting me know about these things. As Brian Eno said if you wanna do anything original try something so annoyingly painstaking that no one has ever bothered to do it :) I'll fix the lyrics next.

**Comment by nxllxvxid** [comment]
> Nah seriously thanks for letting me know about these things. As Brian Eno said if you wanna do anything original try something so annoyingly painstaking that no one has ever bothered to do it :) I'll fix the lyrics next.

sure honestly I'm kinda new to CSS, I know a bit like I can share a couple edits I have with you rn if you want I'm not exactly famililar with trying to add merges plus that's a lot of CSS and you would know a better place for a couple strings:

```/* Change text box selected outline color */
.emby-input:focus,
.emby-textarea:focus {
    border-color: red;
    border-width: 2px;
    transition: border-color 0.3s ease-in-out, border-width 0.3s ease-in-out;
    box-shadow: 0 0 5px red, 0 0 10px red;
}

/*Link color and behavior*/
.button-link {
  color: white;
}
.button-link:hover {
  -webkit-text-decoration: none;
  text-decoration: underline;
  color: red;
}```

**Comment by tedhinklater** [comment]
Nice additions, theyre added!
