### ISSUE TITLE
Slideshow Not working

### ISSUE THREAD

**Issue by DevilsDesigns** [tedhinklater/finality#26]
Using these instructions https://github.com/tedhinklater/finality/tree/main#featured-content-bar-by-bobhasnosoul-and-sethbacon
i get a blank home screen banner.
Im on windows 11 pro im wondering if its different because of the file path edited on the /web/avatars path may be different on windows.
![image](https://github.com/tedhinklater/finality/assets/35183970/663350a9-3723-43d8-85c8-d84638d6b396)

**Comment by nxllxvxid** [comment]
have you attempted to hard refresh with Control F5? also be sure that with the chunk.js file you check both of them because you may have to insert it in both on windows

**Comment by tedhinklater** [comment]
It works on win11,  it might appear blank if the random start max is higher than your movie count (in slideshow.html its set to 400)

**Comment by DevilsDesigns** [comment]
> It works on win11,  it might appear blank if the random start max is higher than your movie count (in slideshow.html its set to 400). Also make sure to empty your browser cache

I have 598 so most likely this is it.

**Comment by tedhinklater** [comment]
Ah if you have over 400 then it should be showing fine. The only things that could really go wrong are the userID >
![Screenshot from 2024-07-08 10-34-01](https://github.com/tedhinklater/finality/assets/66086488/1fd727da-8bf7-4bd2-9f32-3f7e8fd08a7b)

and API Key >

![Screenshot from 2024-07-08 10-35-24](https://github.com/tedhinklater/finality/assets/66086488/29b7cca5-1a0e-4bd7-aee5-52451fb65856)

**Comment by DevilsDesigns** [comment]
Dont we need lists.txt to load our lists?

> Ah if you have over 400 then it should be showing fine. The only things that could really go wrong are the userID > ![Screenshot from 2024-07-08 10-34-01](https://private-user-images.githubusercontent.com/66086488/346508275-1fd727da-8bf7-4bd2-9f32-3f7e8fd08a7b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA0OTQzMTksIm5iZiI6MTcyMDQ5NDAxOSwicGF0aCI6Ii82NjA4NjQ4OC8zNDY1MDgyNzUtMWZkNzI3ZGEtOGJmNy00YmQyLTlmMzItM2Y3ZThmZDA4YTdiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzA5VDAzMDAxOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPThkMGE1YjAxOGRjOGYxYjc3Nzc5ODhjNTgwYTNiNWViZjg3MmQ1YmQ2ZTdhMWYwNzRlNmZkY2I3MWMxOGQ3YjMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.MuJ0vooB4ZASfH7QTX3QeiqJaYAYGA4TdR9kn2VNI7Y)
> 
> and API Key >
> 
> ![Screenshot from 2024-07-08 10-35-24](https://private-user-images.githubusercontent.com/66086488/346508551-29b7cca5-1a0e-4bd7-aee5-52451fb65856.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA0OTQzMTksIm5iZiI6MTcyMDQ5NDAxOSwicGF0aCI6Ii82NjA4NjQ4OC8zNDY1MDg1NTEtMjliN2NjYTUtMWEwZS00YmQ3LWFlZTUtNTI0NTFmYjY1ODU2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzA5VDAzMDAxOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTk4Y2U5NjFjZjRiNDRhODVmMjM1ZmU0YWM5ODNiZjk2YjYxNTk1Y2QyZGQyMDZkNjlhZmUzYWIwNWU5OWVlMjEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.6xNAC9PO4njXGwtUk1U-E5EBDSIamW-P45hhQD-4UQU)

![image](https://github.com/tedhinklater/finality/assets/35183970/1f366312-a61c-417a-81d9-d7931b0d1b89)

**Comment by tedhinklater** [comment]
I never used list.txt, according to [this post](https://forum.jellyfin.org/t-featured-content-bar?page=2&highlight=featured%2Bcontent) "-Reads list.txt (ignoring labels after id codes), if list.txt is not present, grabs 200 movies from server and randomizes a selection of them to display (because i cant find an API call for random selection)"

attached an example list.txt

[list.txt](https://github.com/user-attachments/files/16141929/list.txt)

**Comment by DevilsDesigns** [comment]
> I never used list.txt, according to [this post](https://forum.jellyfin.org/t-featured-content-bar?page=2&highlight=featured%2Bcontent) "-Reads list.txt (ignoring labels after id codes), if list.txt is not present, grabs 200 movies from server and randomizes a selection of them to display (because i cant find an API call for random selection)"
> 
> attached an example list.txt
> 
> [list.txt](https://github.com/user-attachments/files/16141929/list.txt)
> 
> it goes in the avatars folder. If you can let me know if it fixes it that'd be great

weird enough. closing the windows tray app and refreshing on an non incognito window shows it
![image](https://github.com/tedhinklater/finality/assets/35183970/c3f08501-a843-4dea-ae48-b916dc5d7ff1)

but in an incogntio firefox it wont load

**Comment by tedhinklater** [comment]
Did it work without the list.txt?

**Comment by DevilsDesigns** [comment]
> Did it work without the list.txt?

No I had to reboot my jellyfin tray without list.txt and not use incognito mode and it worked after like seconds for it to display

**Comment by tedhinklater** [comment]
hmm I'll leave it open for now in case someone else has the same

**Comment by DevilsDesigns** [comment]
> hmm I'll leave it open for now in case someone else has the same, glad it's working now though

quick questions is there a way to fix it loading extremely slow?

**Comment by tedhinklater** [comment]
that's crazy it takes 1 second on mine. Have you used list.txt ? Try with a small amount of id's to see if it's any faster?

**Comment by nxllxvxxd** [comment]
> > Did it work without the list.txt?
> 
> No I had to reboot my jellyfin tray without list.txt and not use incognito mode and it worked after like seconds for it to display

I reccommend just running jellyfin portable at like the head of your drive. Tray makes stuff a little more complex and annoying
