### ISSUE TITLE
Description is not fixed to the container and container goes past the poster

### ISSUE THREAD

**Issue by TrueBankai416** [tedhinklater/finality#3]
Jellyfin Server 10.9.6

![image](https://github.com/tedhinklater/finality/assets/97103466/31a5e43f-a51a-43e4-bb3c-360ad4d8bf14)

**Comment by TrueBankai416** [comment]
i can remove that bar by disabling `.detailPageSecondaryContainer` but that also removes the background image

**Comment by TrueBankai416** [comment]
Ok, I think I fixed it by adding 
```
.noBackdropTransparency .detailPageSecondaryContainer {
  background-color: #10101000;
}
```

**Comment by tedhinklater** [comment]
If you go to Settings and make sure Backdrops are enabled, it shouldn't do that

**Comment by TrueBankai416** [comment]
> If you go to Settings and make sure Backdrops are enabled, it shouldn't do that

i dont see `backdrops` anywhere. But the splash screen is enabled

**Comment by tedhinklater** [comment]
![backdrops](https://github.com/tedhinklater/finality/assets/66086488/0e65aec9-3b42-4d43-834f-24e243be4c74)

**Comment by TrueBankai416** [comment]
Mine was unchecked

**Comment by tedhinklater** [comment]
Your PR fixed it!
