### ISSUE TITLE
Missing Shuffle Button

### ISSUE THREAD

**Issue by nxllxvxxd** [tedhinklater/finality#30]
Typically there is a shuffle button that is present when you view a TV series and it does not show for some reason? Would fix but have no clue where to even begin to look:
![image](https://github.com/tedhinklater/finality/assets/19805594/b8e4d4f3-32d5-4321-9965-e5a5d5fdbfdb)

**Comment by tedhinklater** [comment]
I just use this one

![Screenshot from 2024-07-08 18-36-01](https://github.com/tedhinklater/finality/assets/66086488/58d40826-6854-4d06-950c-b391eaff3071)

**Comment by nxllxvxxd** [comment]
I was just wondering I have a huge library like over 200 shows sometimes that is hard to get to lmao

**Comment by tedhinklater** [comment]
![Screenshot from 2024-07-09 01-08-42](https://github.com/tedhinklater/finality/assets/66086488/67fe2911-d124-4263-b3ab-48561446b4c7)

working on a fix

**Comment by nxllxvxxd** [comment]
I fuck with it hard that is actually perfect, subtle yet noticable
