### ISSUE TITLE
Special Features are pretty special if you catch my drift

### ISSUE THREAD

**Issue by nxllxvxxd** [tedhinklater/finality#34]
![image](https://github.com/user-attachments/assets/b0d9eddb-f3cf-4bf1-afc8-8558c91fde1b)
yeah just this lmfaooooo, i'm sorry i know github is supposed to be like professional but I can't

**Comment by tedhinklater** [comment]
I can't believe I actually thought I'd finished this theme after 6 days

**Comment by tedhinklater** [comment]
back to basics ![g6](https://github.com/user-attachments/assets/070ab65a-7bd8-4801-b953-d0b63c033208)

**Comment by nxllxvxxd** [comment]
shit i don't know if you can do it I think you send it fucks with the music or something I think but if you could just put the movies in a little drawer at the bottom of the collection like tv show seasons

**Comment by tedhinklater** [comment]
Is it that you want the logo in the middle to be visible? Im thinking they can stay there and be transparent until hovered, or be visible and overlapping like a deck of cards, or be visible and on the left have a fan-out to the right animation like a deck of cards when hovered

**Comment by tedhinklater** [comment]
Like this ![unknown_2024 07 15-13 16_1](https://github.com/user-attachments/assets/a31daf2e-8994-4203-be02-35fc0b8eb6c0)

**Comment by nxllxvxxd** [comment]
Honestly that can work that looks pretty good i like it, lmfao i'm sorry i keep making you work on this 💀

**Comment by tedhinklater** [comment]
you're crazy to use it daily you should be on a government list xD

**Comment by nxllxvxxd** [comment]
> you're crazy to use it daily you should be on a government list xD

i most likely am with what i download
