### ISSUE TITLE
Genres clip into cover

### ISSUE THREAD

**Issue by nxllxvxxd** [tedhinklater/finality#36]
![image](https://github.com/user-attachments/assets/62642e19-9ae0-4605-bbd3-723c3a321f6a)
If you have multiple genres say in something like a movie collection it will clip through and make you unable to do things like favorite the collection

**Comment by tedhinklater** [comment]
ty ty ty

**Comment by nxllxvxxd** [comment]
> ty ty ty

dog also let me know ever if like you want me to fuck off i really don't know how much you wanna work on this necessarily especaially since you told me you were planning on making it only in 6 days
