### ISSUE TITLE
Appears on section wonky 1440

### ISSUE THREAD

**Issue by nxllxvxxd** [tedhinklater/finality#45]
![2024-07-19 05 40 19,274](https://github.com/user-attachments/assets/f641404e-f110-43e5-b42d-57777fd23252)

Its just wonky lmao I don't know what to say it seems a little too far to the left though I am unsure of where it is actually intended to be

**Comment by tedhinklater** [comment]
Lol its meant to be below the cover... That section is definitely cursed I need to find out why it's so messed up. I remember why I hid it.

**Comment by nxllxvxxd** [comment]
I wish there were designators in the css for specific media like tv shows movies etc, like how there is for the favorites tab and shit

**Comment by nxllxvxxd** [comment]
It is fixed on my end I don't know if your end is okay but 1440 is fine so I'll close this issue

**Comment by tedhinklater** [comment]
Awesome thanks.
