### ISSUE TITLE
wrong color scheme for css

### ISSUE THREAD

**Issue by DevilsDesigns** [tedhinklater/finality#46]
The Admin panel has the colour but the main page has black and white. I tried this in a private windows. Currently on 10.9.7 just upgraded from 10.9.6 and redid all css modifications and this happened.
![image](https://github.com/user-attachments/assets/39ad72c6-17f9-4ab1-aea7-f2dc7e14422d)
![image](https://github.com/user-attachments/assets/91431477-94c5-49e1-9986-84428e70393f)

**Comment by DevilsDesigns** [comment]
![Uploading image.png…]()

**Comment by tedhinklater** [comment]
On the left? Yeah I think it would look better matching

**Comment by tedhinklater** [comment]
Thanks! 
![dash panel](https://github.com/user-attachments/assets/62b16d35-f3ba-41f7-b68d-827c3c83d2a1)

**Comment by DevilsDesigns** [comment]
> Thanks! 
> ![dash panel](https://github.com/user-attachments/assets/62b16d35-f3ba-41f7-b68d-827c3c83d2a1)
> 

I thought this was the difference between black and white and color which has red

**Comment by tedhinklater** [comment]
ahhh no the difference is the backdrop, there's always people saying colour in the backdrop is too noisy and want B&W.

**Comment by DevilsDesigns** [comment]
> ahhh no the difference is the backdrop, there's always people saying colour in the backdrop is too noisy and want B&W.

can you give the code to change for red i really liked that color scheme compared to the white?

**Comment by tedhinklater** [comment]
Youre right I've actually changed it to red it should show the change soon

**Comment by tedhinklater** [comment]
![350803146-1311bff5-8db8-43a6-9037-c3778a37e696](https://github.com/user-attachments/assets/c2ee6d87-30fd-437c-b37b-cdb2df03f5b5)

**Comment by DevilsDesigns** [comment]
> ![350803146-1311bff5-8db8-43a6-9037-c3778a37e696](https://private-user-images.githubusercontent.com/66086488/350807852-c2ee6d87-30fd-437c-b37b-cdb2df03f5b5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE2MTA1NDIsIm5iZiI6MTcyMTYxMDI0MiwicGF0aCI6Ii82NjA4NjQ4OC8zNTA4MDc4NTItYzJlZTZkODctMzBmZC00MzdjLWIzN2ItY2RiMmRmMDNmNWI1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzIyVDAxMDQwMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTJjMGNhM2UzM2M2ZjFhNGRkMWQ3YjA5MjY3MGVlZGFkNTViZmU0ZWViMzkwZDBhMjlkMzRiYWRlZjU5NWMxNWImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.v58sEy693-CrC_RN3uWkSCHXK8Z-4Q8ypVuMY5VN-kA)

your using the color css right?

**Comment by tedhinklater** [comment]
the default is now red

**Comment by DevilsDesigns** [comment]
> the default is now red

thank you! It works when i manually update the CSS Code. So I guess we just need to wait for the jdn to update the code with the new link sometimes it takes 24-48hrs
