### ISSUE TITLE
Live TV Logo Not Changing Even When Manually Settings

### ISSUE THREAD

**Issue by nxllxvxxd** [tedhinklater/finality#48]
I don't know if this is a result of the css or not but even when i manually replace my image for Live TV it doesn't show up and when it does it is only until reload
![2024-07-20 16 18 53,100](https://github.com/user-attachments/assets/cac70fb5-fb61-4ef7-a5e5-a042ff2bfef6)

**Comment by tedhinklater** [comment]
I used to have the same problem its a jellyfin bug. I think you have to set the image for at least a week until it's permanent, then you won't have to reload the page to see it. Annoying, I know.
