### ISSUE TITLE
slideshow text is very small on 1440p

### ISSUE THREAD

**Issue by nxllxvxxd** [tedhinklater/finality#57]
![2024-07-31 06 23 12,264](https://github.com/user-attachments/assets/3f4a5a7f-7ddd-4bd0-a40e-845878687e49)
When using your version of slideshow.html (which I fuckin love by the way it is beautiful and I think you fixed the whole issue of items with no logo and make it where they don't appear though I could be wrong) the description text is **realllllllllly** small

**Comment by nxllxvxxd** [comment]
Suggestion because I personally prefer the way that it looks but if you go under ``.plot`` and make the ``font-weight`` ``bolder`` it honestly looks a lot better and easier to read:
![2024-07-31 06 41 35,504](https://github.com/user-attachments/assets/c3534d89-68f9-486a-a6d4-be5e91c8511d)

**Comment by tedhinklater** [comment]
Slideshow.html is updated! Ty
