### ISSUE TITLE
User icon/avatar is gone

### ISSUE THREAD

**Issue by TrueBankai416** [tedhinklater/finality#6]
Server 10.9.6
Happens on all devices, Mobile, Web, Windows Client

![image](https://github.com/tedhinklater/finality/assets/97103466/05d13e6b-9eb6-425c-95fa-fb8f1c4e3694)

**Comment by DevilsDesigns** [comment]
hey that was my issue to post lol
![image](https://github.com/tedhinklater/finality/assets/35183970/3068f5d7-cf0c-42e8-ba9d-e42f11e26e47)

**Comment by TrueBankai416** [comment]
It shows up in the dashboard
![image](https://github.com/tedhinklater/finality/assets/97103466/a9bdded3-8cfa-46f7-bf12-7065fc2d8b09)

**Comment by tedhinklater** [comment]
yeah I accidentally set .paper-icon-button-light to transparent, should have been .paper-icon-button-light:hover

It takes me ages to spot this stuff so thanks for your help!

**Comment by DevilsDesigns** [comment]
> yeah I accidentally set .paper-icon-button-light to transparent, should have been .paper-icon-button-light:hover
> 
> It takes me ages to spot this stuff so thanks for your help!

did you fix this yet?
