### ISSUE TITLE
Right Click Menu Being Cut off

### ISSUE THREAD

**Issue by DevilsDesigns** [tedhinklater/finality#60]
![image](https://github.com/user-attachments/assets/c6cb5f74-6067-49b6-8b23-2fe4fc83297f)
the right click menu is completely cut off on mobile and web.

**Comment by DevilsDesigns** [comment]
its wird its only on some of the items
![image](https://github.com/user-attachments/assets/fa10be44-717c-4912-b3f5-9c678fd94000)

**Comment by tedhinklater** [comment]
I'm trying but I can't replicate this... Any more info? Browser/Server version/display resolution?

**Comment by tedhinklater** [comment]
It looks like you're not logged in as an admin?

**Comment by DevilsDesigns** [comment]
> It looks like you're not logged in as an admin?

Weird enough it's now working. I have done nothing aside from upgrading to 10.9.9 from 10.9.7. so maybe a caching issue?
