### ISSUE TITLE
Media buttons do not appear on ultrawide monitor

### ISSUE THREAD

**Issue by wathergeen** [tedhinklater/finality#62]
For some reason, the playback buttons don't appear when I use the theme on an ultrawide monitor.

- Ultrawide Monitor
![image](https://github.com/user-attachments/assets/a72322c5-de81-492d-a7fa-cf65cc68fb9f)

- Convetional 16:9 monitor
![image](https://github.com/user-attachments/assets/98620c79-79ae-41be-8d7b-002f4808f444)

**Comment by tedhinklater** [comment]
Can I ask what the exact resolution of the screen is? It'll help

**Comment by tedhinklater** [comment]
By the way, make sure you click your profile picture in Jellyfin, go to Display, scroll down to Backdrops and turn it on. It'll remove that grey bar. 

I don't have ultrawide to test but I'd appreciate if you could add this line and let me know if it works : 

@import url("https://cdn.jsdelivr.net/gh/tedhinklater/finality@main/UltrawideFix.css");

**Comment by wathergeen** [comment]
> Can I ask what the exact resolution of the screen is? It'll help

The resolution is 2560x1080. An FHD Ultrawide monitor.

Here some screenshots of the change you made
- Series preview
![image](https://github.com/user-attachments/assets/b74e5763-93b4-47cb-a1c0-f8084de0a774)
- Series Season preview
![image](https://github.com/user-attachments/assets/d210a862-d56f-4d5b-8f99-acc6c5968463)
- Episode Preview
![image](https://github.com/user-attachments/assets/ca489d58-fe67-44ca-a413-e94dbc4bac23)

**Comment by tedhinklater** [comment]
oh wow it looks bad :D thank you so much for the screenshots I can fix it with the info

**Comment by tedhinklater** [comment]
Ok it might take a while for the jsdelivr link to update but it should be fixed

**Comment by wathergeen** [comment]
Now it is working perfectly

- Series preview
- Season preview
- Episode preview

**Comment by tedhinklater** [comment]
Thanks for the updated screenshots; I've just repositioned the description, and fixed the cast & crew so it shows 7 (not 7 and a half) and so the button on the right is visible. That should be it and should update shortly. Thanks again for taking the time to help it's really appreciated.
