### ISSUE TITLE
Settings UI bugged

### ISSUE THREAD

**Issue by saurabhshinde14** [tedhinklater/finality#65]
Hi,

Thanks for implementing the changes I mentioned.

So "My media (small)" buttons are centered, but so are other things from settings.

![Screenshot 2024-09-13 114728](https://github.com/user-attachments/assets/2befbafd-0710-4f85-8b75-cce13fecf79d)
![Screenshot 2024-09-13 115144](https://github.com/user-attachments/assets/d334a81c-a003-40b8-a131-2e391157db1f)

The edits you made doesn't work on Jellyfin Media Player sadly.

![Screenshot 2024-09-13 120250](https://github.com/user-attachments/assets/024abd7b-a3e7-4746-8bcb-7c2abba1d0b8)

**Comment by tedhinklater** [comment]
[Fixed](https://github.com/tedhinklater/finality/commit/6fab92564fc20f1635b7f3dfd4379aa6f2e313fc)
