### ISSUE TITLE
Request?

### ISSUE THREAD

**Issue by mgoodall63** [tedhinklater/finality#67]
Would it be possible to center Collections, Movies, TV Shows and also the continue watching as below?

![image](https://github.com/user-attachments/assets/58641c17-9312-4b59-9b6e-f666116a36c4)

I tired to look through the code to do it, but i can see where the element is being called from to make the required change..

![image](https://github.com/user-attachments/assets/6ccf5dae-6091-4f83-a4f0-c51950a505de)

Really enjoying the theme, so thanks to you all for the development put into it!

**Comment by tedhinklater** [comment]
Looks nice! I've added the [update](https://github.com/tedhinklater/finality/commit/e8f982e9f229510e14b795d3e6a4bee9b3c2672a), should come through shortly

**Comment by mgoodall63** [comment]
That looks fantastic! Thank you so much for the quick turn around!

<img width="1705" alt="image" src="https://github.com/user-attachments/assets/c16e4e29-1f9a-41bb-87f3-4bd335957b7e">

**Comment by tedhinklater** [comment]
Hey I undid the change as there were some problems, but this is the code to get the centre look if you want to edit/add it to yours

.layout-desktop #homeTab .emby-scroller-container {
    justify-content: center;
    display: flex;
	transform: translateX(-50%);
	left: 50vw;
}

.layout-desktop #homeTab .emby-scroller {
	padding-left: max(env(safe-area-inset-left),3%);
	padding-right: max(env(safe-area-inset-right),3%);
}

.layout-desktop .sectionTitleContainer-cards, .sectionTitle.sectionTitle-cards.padded-left {
    position: absolute;
	transform: translateX(-50%);
	left: 50vw;
	font-size: 1.25em;
	font-weight: 600 !important;
}

.layout-desktop .verticalSection.section1.emby-scroller-container .sectionTitle.sectionTitle-cards.padded-left {
	font-size: 1.25em !important;
	top: -0.7em;
}
