### ISSUE TITLE
Titles/headers & alignment issues

### ISSUE THREAD

**Issue by fellowslothb** [tedhinklater/finality#68]
Since around a few days ago, everything has started to be center aligned to the screen, all the titles and headers have moved into the center, even the library items have started center aligning for some reason.

Titles for the suggestions and upcoming content are displaying weird too (as shown below)

I haven't touched a thing recently for it to have suddenly changed but maybe I've done something previously and it's only just taken effect. But whatever I have done I've made it look really weird xD 

Just wonder if there's a way to return it all to the left alignment I prefer (and to fix the cut off titles) - Screenshots aren't cut off, that is the edge of my screen.
For reference I'm using a 2560x1440 display, but I have also used a 1920x1080 display and having the same issue.

![image](https://github.com/user-attachments/assets/d82c9749-904f-41cb-bf3a-a3d5d17824ff)
![image](https://github.com/user-attachments/assets/48b71cd1-d0cc-4233-8b94-e4f063fb27ef)
![image](https://github.com/user-attachments/assets/be7ac0e4-f074-4164-8901-87b1566d4561)

**Comment by tedhinklater** [comment]
ah my bad, it's [fixed](https://github.com/tedhinklater/finality/commit/58347f0885e0e8e4fbf17077bf0329b83d7f45d0) now, was trying something out and didn't notice that problem, thanks for letting me know! Should update shortly, sorry for the mistake there
