### ISSUE TITLE
Merging

### ISSUE THREAD

**Issue by DevilsDesigns** [tedhinklater/finality#9]
Make sure your committing the pulls. it doesnt seem there going through on the css

**Comment by TrueBankai416** [comment]
i see them on the css?

**Comment by DevilsDesigns** [comment]
i do too but when we run the https://cdn.jsdelivr.net/gh/DevilsDesigns/finality@patch-1/finality.css it shows the changes with yours it doesnt for some odd reason

**Comment by tedhinklater** [comment]
Ah jsdelivr can take up to 48hrs sometimes

**Comment by TrueBankai416** [comment]
> i do too but when we run the https://cdn.jsdelivr.net/gh/DevilsDesigns/finality@patch-1/finality.css it shows the changes with yours it doesnt for some odd reason
I fixed this on my end by replacing the branch name with `@latest`
so mine changed from 

https://cdn.jsdelivr.net/gh/TrueBankai416/Jellyfin-Themes@main/finality.css
to
https://cdn.jsdelivr.net/gh/TrueBankai416/Jellyfin-Themes@latest/finality.css

**Comment by DevilsDesigns** [comment]
aah good to know

> Ah jsdelivr can take up to 48hrs sometimes

**Comment by TrueBankai416** [comment]
but now it seems to not be updating again so scratch that. 48hrs it is then

**Comment by DevilsDesigns** [comment]
looks good

**Comment by tedhinklater** [comment]
> I fixed this on my end by replacing the branch name with `@latest` so mine changed from
> 
> https://cdn.jsdelivr.net/gh/TrueBankai416/Jellyfin-Themes@main/finality.css to https://cdn.jsdelivr.net/gh/TrueBankai416/Jellyfin-Themes@latest/finality.css

TIL
